## Wrangling parks data

### Goals of the Task


The parks and recreation data consists of two data sets. 

- The smaller data set contains address, longitude and latitude for Seattle parks (each row is a park). 
- The second data set (features) indicates which facilities a park has (each row is a facility in a park) such as picnic areas, basketball courts and football pitches. 

The aim of this task is to combine and reshape the data into a wide rather than long frame where each row is a park, and there is a Boolean column for each feature type.

#### Step 1 : use pandas to read the two parks & recreation files as data frames
- import pandas as pd 
- use pandas read_csv to create a parks data frame and a facilities data frame 
- ensure you are pointing at the correct file path for the data source (you may have to navigate in your notebook!)

#### Step 2 : reformat the column headers in lower case 

the data sets have some inconsistencies in the header case on columns so this should be fixed using the str.lower() method. 

df.columns = df.columns.str.lower() function

#### Step 3 : join the data frames together 

use the pandas merge method to combine the two data frames into a new single data frame, using the pmaid column as the merge key. 

https://www.geeksforgeeks.org/merge-two-pandas-dataframes-by-matched-id-number/

#### step 4: drop unneccesary columns

the columns we want to keep in the resulting data frame are 

- zip code
- x and y coords 
- location id 
- park name 
- feature description 

drop all remaining columns

#### step 5: turn the feature column into multiple boolean columns 

use the pandas pivot_table method, pivot the feature desciption column into multiple columns which will change the shape of the data from long to wide

- pd.pivot_table(df, index=[park], columns=[feature],aggfunc="count")

replace the NaN entries in the resulting df with 0 with the pandas fillna() method

In [1]:
import pandas as pd

In [24]:
df=pd.read_csv('all_data/Seattle_Parks_and_Recreation_Parks_Features.csv')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1558 entries, 0 to 1557
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PMAID         1558 non-null   int64
 1   Name          1558 non-null   object
 2   Alt_Name      222 non-null    object
 3   xPos          1521 non-null   float64
 4   yPos          1522 non-null   float64
 5   Feature_ID    1558 non-null   int64
 6   hours         1555 non-null   object
 7   Feature_Desc  1558 non-null   object
 8   CHILD_DESC    638 non-null    object
 9   FIELD_TYPE    216 non-null    object
 10  YOUTH_ONLY    1558 non-null   bool
 11  LIGHTING      1558 non-null   bool
 12  Location 1    1521 non-null   object
dtypes: bool(2), float64(2), int64(2), object(7)
memory usage: 137.1+ KB

In [26]:
df = df[['PMAID', 'Name', 'Feature_Desc']]

In [27]:
df.head()

   PMAID                     Name              Feature_Desc
0    281  12th and Howe Play Park                 Play Area
1   4159     12th Ave S Viewpoint                      View
2   4010    14th Ave NW Boat Ramp  Boat Launch (Hand Carry)
3   4010    14th Ave NW Boat Ramp   Boat Launch (Motorized)
4   4010    14th Ave NW Boat Ramp                Waterfront

In [23]:
df.shape

(1558, 2)

In [32]:
df1=pd.pivot_table(df, index=['PMAID'], columns=['Feature_Desc'],aggfunc="count")

In [33]:
df1.shape

(309, 68)

In [34]:
df1.head(20)

                                Name                                   \
Feature_Desc Adult Fitness Equipment BMX Dirt Jumps Baseball/Softball
PMAID
43                               NaN            NaN               NaN
80                               NaN            NaN               NaN
114                              NaN            NaN               1.0
200                              NaN            NaN               NaN
234                              NaN            NaN               NaN
237                              NaN            NaN               NaN
240                              NaN            NaN               NaN
241                              NaN            NaN               1.0
242                              NaN            NaN               2.0
243                              NaN            NaN               NaN
244                              NaN            NaN               NaN
246                              NaN            NaN               NaN
247                              NaN            NaN               NaN
248                              NaN            NaN               1.0
249                              NaN            NaN               NaN
250                              NaN            NaN               NaN
251                              NaN            NaN               4.0
252                              NaN            NaN               NaN
260                              NaN            NaN               NaN
263                              NaN            NaN               NaN

                                                                       \
Feature_Desc Basketball (Full) Basketball (Half) Bike Polo Bike Trail
PMAID
43                         NaN               NaN       NaN        NaN
80                         NaN               NaN       NaN        NaN
114                        1.0               NaN       NaN        NaN
200                        NaN               NaN       NaN        NaN
234                        NaN               NaN       NaN        NaN
237                        NaN               NaN       NaN        NaN
240                        NaN               NaN       NaN        NaN
241                        1.0               1.0       NaN        NaN
242                        NaN               2.0       NaN        NaN
243                        NaN               1.0       NaN        NaN
244                        NaN               NaN       NaN        NaN
246                        NaN               NaN       NaN        NaN
247                        NaN               NaN       NaN        NaN
248                        NaN               1.0       NaN        NaN
249                        NaN               NaN       NaN        NaN
250                        1.0               NaN       NaN        NaN
251                        NaN               NaN       NaN        NaN
252                        NaN               NaN       NaN        NaN
260                        NaN               NaN       NaN        NaN
263                        NaN               NaN       NaN        NaN

                                                                            \
Feature_Desc Boat Launch (Hand Carry) Boat Launch (Motorized) Boat Moorage
PMAID
43                                NaN                     NaN          NaN
80                                1.0                     NaN          NaN
114                               NaN                     NaN          NaN
200                               NaN                     NaN          NaN
234                               NaN                     NaN          NaN
237                               NaN                     NaN          NaN
240                               1.0                     NaN          NaN
241                               NaN                     NaN          NaN
242                               NaN                     NaN          NaN
243                               1.0                     NaN          NaN
244                               NaN                     NaN          NaN
246                               NaN                     NaN          NaN
247                               NaN                     NaN          NaN
248                               NaN                     NaN          NaN
249                               NaN                     NaN          NaN
250                               NaN                     NaN          NaN
251                               NaN                     NaN          NaN
252                               NaN                     NaN          NaN
260                               NaN                     NaN          NaN
263                               NaN                     NaN          NaN

              ...                                           \
Feature_Desc  ... Tidelands Track U-8 Soccer Ultimate View
PMAID         ...
43            ...       NaN   NaN        NaN      NaN  1.0
80            ...       NaN   NaN        NaN      NaN  1.0
114           ...       NaN   NaN        NaN      NaN  1.0
200           ...       NaN   NaN        NaN      NaN  NaN
234           ...       NaN   NaN        NaN      NaN  NaN
237           ...       NaN   NaN        NaN      NaN  NaN
240           ...       NaN   NaN        NaN      NaN  1.0
241           ...       NaN   NaN        NaN      NaN  NaN
242           ...       NaN   NaN        NaN      NaN  NaN
243           ...       NaN   NaN        NaN      NaN  1.0
244           ...       NaN   NaN        NaN      NaN  NaN
246           ...       NaN   NaN        NaN      NaN  NaN
247           ...       NaN   NaN        NaN      NaN  NaN
248           ...       NaN   NaN        NaN      NaN  NaN
249           ...       NaN   NaN        NaN      NaN  NaN
250           ...       NaN   NaN        NaN      NaN  NaN
251           ...       NaN   NaN        NaN      NaN  1.0
252           ...       NaN   NaN        NaN      NaN  1.0
260           ...       NaN   NaN        NaN      NaN  NaN
263           ...       NaN   NaN        NaN      NaN  NaN

                                                                              \
Feature_Desc Wading Pool or Water Feature Waterfront Weddings and Ceremonies
PMAID
43                                    NaN        NaN                     NaN
80                                    NaN        1.0                     NaN
114                                   1.0        NaN                     1.0
200                                   NaN        NaN                     NaN
234                                   NaN        NaN                     NaN
237                                   NaN        NaN                     NaN
240                                   NaN        1.0                     1.0
241                                   NaN        NaN                     NaN
242                                   1.0        NaN                     NaN
243                                   NaN        2.0                     1.0
244                                   NaN        NaN                     NaN
246                                   NaN        NaN                     NaN
247                                   NaN        NaN                     NaN
248                                   NaN        NaN                     NaN
249                                   NaN        NaN                     NaN
250                                   1.0        NaN                     NaN
251                                   1.0        NaN                     NaN
252                                   NaN        NaN                     1.0
260                                   NaN        NaN                     NaN
263                                   NaN        NaN                     NaN


Feature_Desc Woods Zipline
PMAID
43             NaN     NaN
80             NaN     NaN
114            NaN     NaN
200            NaN     NaN
234            1.0     NaN
237            NaN     NaN
240            1.0     NaN
241            NaN     NaN
242            NaN     NaN
243            NaN     NaN
244            NaN     NaN
246            1.0     NaN
247            1.0     NaN
248            NaN     NaN
249            NaN     NaN
250            NaN     NaN
251            NaN     NaN
252            NaN     NaN
260            NaN     NaN
263            NaN     NaN

[20 rows x 68 columns]

In [35]:
df1.fillna(0)

                                Name                                   \
Feature_Desc Adult Fitness Equipment BMX Dirt Jumps Baseball/Softball
PMAID
43                               0.0            0.0               0.0
80                               0.0            0.0               0.0
114                              0.0            0.0               1.0
200                              0.0            0.0               0.0
234                              0.0            0.0               0.0
...                              ...            ...               ...
1000292                          0.0            0.0               0.0
1000342                          0.0            0.0               0.0
1000393                          0.0            0.0               0.0
1000399                          0.0            0.0               0.0
1100393                          0.0            0.0               2.0

                                                                       \
Feature_Desc Basketball (Full) Basketball (Half) Bike Polo Bike Trail
PMAID
43                         0.0               0.0       0.0        0.0
80                         0.0               0.0       0.0        0.0
114                        1.0               0.0       0.0        0.0
200                        0.0               0.0       0.0        0.0
234                        0.0               0.0       0.0        0.0
...                        ...               ...       ...        ...
1000292                    0.0               0.0       0.0        0.0
1000342                    0.0               0.0       0.0        0.0
1000393                    0.0               0.0       0.0        0.0
1000399                    0.0               0.0       0.0        0.0
1100393                    0.0               0.0       0.0        0.0

                                                                            \
Feature_Desc Boat Launch (Hand Carry) Boat Launch (Motorized) Boat Moorage
PMAID
43                                0.0                     0.0          0.0
80                                1.0                     0.0          0.0
114                               0.0                     0.0          0.0
200                               0.0                     0.0          0.0
234                               0.0                     0.0          0.0
...                               ...                     ...          ...
1000292                           0.0                     0.0          0.0
1000342                           0.0                     0.0          0.0
1000393                           0.0                     0.0          0.0
1000399                           0.0                     0.0          0.0
1100393                           0.0                     0.0          0.0

              ...                                           \
Feature_Desc  ... Tidelands Track U-8 Soccer Ultimate View
PMAID         ...
43            ...       0.0   0.0        0.0      0.0  1.0
80            ...       0.0   0.0        0.0      0.0  1.0
114           ...       0.0   0.0        0.0      0.0  1.0
200           ...       0.0   0.0        0.0      0.0  0.0
234           ...       0.0   0.0        0.0      0.0  0.0
...           ...       ...   ...        ...      ...  ...
1000292       ...       0.0   0.0        0.0      0.0  0.0
1000342       ...       0.0   0.0        0.0      0.0  0.0
1000393       ...       0.0   0.0        0.0      0.0  0.0
1000399       ...       0.0   0.0        0.0      0.0  0.0
1100393       ...       0.0   0.0        0.0      0.0  0.0

                                                                              \
Feature_Desc Wading Pool or Water Feature Waterfront Weddings and Ceremonies
PMAID
43                                    0.0        0.0                     0.0
80                                    0.0        1.0                     0.0
114                                   1.0        0.0                     1.0
200                                   0.0        0.0                     0.0
234                                   0.0        0.0                     0.0
...                                   ...        ...                     ...
1000292                               0.0        0.0                     1.0
1000342                               0.0        0.0                     0.0
1000393                               0.0        0.0                     0.0
1000399                               0.0        0.0                     1.0
1100393                               0.0        0.0                     0.0


Feature_Desc Woods Zipline
PMAID
43             0.0     0.0
80             0.0     0.0
114            0.0     0.0
200            0.0     0.0
234            1.0     0.0
...            ...     ...
1000292        0.0     0.0
1000342        0.0     0.0
1000393        0.0     0.0
1000399        0.0     0.0
1100393        0.0     0.0

[309 rows x 68 columns]

#### Step 6: validate the data
- use EDA techniques including visualisation to validate the reshaping process